services:
  postgresdb:
    image: postgres:latest
    # container_name: postgresdb
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "Pass123!"
    networks:
      - dynamic-search

  core-service:
    image: khoitmp/core-service:latest
    # container_name: core-service
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      Logging__LogLevel__Default: "Trace"
      Logging__LogLevel__Microsoft: "Warning"
      Logging__LogLevel__System: "Warning"
      Logging__LogLevel__Microsoft.Hosting.Lifetime: "Information"
      Logging__LogLevel__Microsoft.EntityFrameworkCore: "Information"
      ConnectionStrings__Default: "User ID=postgres;Password=Pass123!;Host=postgresdb;Port=5432;Database=core;Pooling=true"
    ports:
      - "11000:80"
    depends_on:
      - postgresdb
    networks:
      - dynamic-search

  core-migration:
    image: khoitmp/core-service:migration-latest
    # container_name: core-migration
    restart: on-failure
    depends_on:
      - postgresdb
    networks:
      - dynamic-search

networks:
  dynamic-search:
