services:
  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - dynamic-search

  core-migration:
    image: khoitmp/core-service:migration-latest
    container_name: core-migration
    restart: on-failure
    depends_on:
      - postgresdb
    networks:
      - dynamic-search

networks:
  dynamic-search:
    name: dynamic-search
    driver: bridge
    external: false